import random
from unittest.main import main
class User:
    '''
    this is a class for adding user 
    '''

    users=[] #empty users

    def __init__(self,userName,email,password,confirmPassword):
        self.email=email
        self.password=password
        self.confirmPassword=confirmPassword

    def createUser(email,password,confirmPassword):
        '''
        an instance that will create a new user
        '''
        newUser =User(email,userName,password,confirmPassword)
        return newUser

    def saveUser(email,userName,password):
        """
        this method will save the user details
        """
        newUser =[email,userName,password]
        User.users.append(newUser)

    def loginMessage():
        """
        this method confirms if succesful in login in
        """

    @classmethod
    #this is a class decorator to display users
    def display_users(self):
        for user in self.users:
            print(user)

    @classmethod
    #class decorator to delete users
    def del_users(self):
        User.users.remove(self)
class Credentials:
    '''
    this is a class fo credentials
    '''

    def __init__(self,userName,password):
        """
        this is an instance to create credentials
        """
        self.userName= userName
        self.password=password

    Credentials=[]

    def createNewCredentials(self,userName,password):
        """
        method to create new credentials
        """
        newCredentials=Credentials(userName,password)
        return newCredentials

    def saveCredentials(self,userName,password):
        """
        method to save new credentials
        """
        Credentials.credentials.append(self)

    def displayCredentials(self):
        for credential in Credentials.credentials:
            print(credential)
    def checkExistance(self,userName):
        """
        method that checks the existance of user data
        """
        if Credentials.credentials:
            for credential in Credentials.credentials:
                if credential.userName==userName:
                    return True
                print("details provided already exist")
            else:
                print("info provided notyet saved")

    def delete_credentials(accountName):
        """
        this will delete user credentials
        """
        for credential in Credentials.credentials:
                if credential.userName==accountName:
                    Credentials.credentials.remove(credential)

def main():
    print("Hi there and welcome")
    while True:
        print("*"*40)
        usee_name= input("Enter your user name")
        loginOptions=input(f"hello {usee_name}. kindly use these short codes to select your option:\n cc -create account.\n lg -login\n dc -Display credentials\n ex -exit")
        print ("*"*40)
        if loginOptions=='cc':
            userName= input("enter your username:\n")

            passwordOption= input("choose your option:\n 1. Enter password\n 2. use autogenerated password\n")

            if passwordoption == "1":                
                password = input("Enter password: \n")
                
                confirmPassword = input("Confirm password: \n")

                if password == confirmPassword:
                    print("Welcome to passlocker. Login")
                    User.createUser(userName,password,confirmPassword)
                    User.saveUser(userName, password)
                    print(f"Account created successfully with {userName} as username")

                    elif passwordoption == "2":
                password = random.randint(10000, 90000)
                User.saveUser(userName, password)

                print(f"Account created successfully with user {userName}.\n")
                print("Password is: ")
                print(password)

                elif login_options == 'lg':
                    print("Welcome to passlocker. Login\n")
                    print("Enter your username: \n")
                    login_userName = input()
                    print("\n")

                    print("Enter your password: \n")
                    
            login_password = input()
            for credential in User.users:
                if credential[0] == login_username and credential[1] == int(login_password):
                    prompt_selection =

